config/routes.rb
BresApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogposts, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/bio', to: 'static_pages#bio', via: 'get'
  match '/resume', to: 'static_pages#resume', via: 'get'
  match '/portfolio', to: 'static_pages#portfolio', via: 'get'

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :subject, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
	self.per_page = 5
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogposts, dependent: :destroy
	has_secure_password
  	before_save { email.downcase! }
  	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  	private

    	def create_remember_token
      		self.remember_token = User.encrypt(User.new_remember_token)
    	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy]

	def index
	end

	def create
		@blogpost = current_user.blogposts.build(blogpost_params)
		@user = current_user
		@blogposts = @user.blogposts.paginate(page: params[:page])
		if @blogpost.save
			flash[:success] = "Blog post created!"
			redirect_to current_user
		else
			render template: "users/show"
		end
	end

	def destroy
	    Blogpost.find(params[:id]).destroy
	    flash[:success] = "Post deleted."
	    redirect_to current_user
  	end

	def show
	end

	private

		def blogpost_params
			params.require(:blogpost).permit(:content, :subject)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@blogposts = Blogpost.paginate(page: params[:page])
  end

  def show
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def feed
    blogpost.where("user_id = ?", id)
  end

	def show
		@user = User.find(params[:id])
    @blogposts = @user.blogposts.paginate(page: params[:page])
    @blogpost = @user.blogposts.build
	end

	def new
		@user = User.new
	end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome! Thanks for joining."
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Bre Bader - Author"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def bootstrap_class_for flash_type
    	case flash_type
	      when :success
	        "alert-success"
	      when :error
	        "alert-danger"
	      when :alert
	        "alert-info"
	      when :notice
	        "alert-warning"
	      else
	        flash_type.to_s
   		end
  	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
	    remember_token = User.new_remember_token
	    cookies.permanent[:remember_token] = remember_token
	    user.update_attribute(:remember_token, User.encrypt(remember_token))
	    self.current_user = user
	end

	def signed_in?
    	!current_user.nil?
  	end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

	def current_user=(user)
    	@current_user = user
	end

	def current_user
  	remember_token = User.encrypt(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
	end

  def current_user?(user)
    user == current_user
  end

	def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogposts/_blogpost.html.erb
<article class = "panel">
	<header>
		<h3><%= blogpost.subject %>
			<% if signed_in? && current_user.admin? %>
				<span style="float:right;"><%= link_to "Delete", blogpost, method: :delete, data: { confirm: "You sure?" } %></span>
			<% end %>
		</h3>
	</header>

  	<p><%= blogpost.content %></p>

  	<footer class = "text-muted">
  		<p>
	  		<small>Posted <%= time_ago_in_words(blogpost.created_at) %> ago.
	  		</small>

	    	<span class= "byline">
	    		<small>
	    			By <%= link_to blogpost.user.name, about_path %>
	    		</small>
	    	</span>
	    </p>
  	</footer>
</article>

app/views/layouts/_booklist.html.erb
<h2>Reading Now</h2>
<div class = "media">
	<div class = "pull-left">
		<img class="img-thumbnail" src="holder.js/64x100" alt="Book Placeholder Image">
	</div>
	<div class = "media-body">
		<p>Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.</p>
	</div>
</div>
<div class = "media">
	<div class = "pull-right">
		<img class="img-thumbnail" src="holder.js/64x100" alt="Book Placeholder Image">
	</div>
	<div class = "media-body">
		<p>Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.</p>
	</div>
</div>
<div class = "media">
	<div class = "pull-left">
		<img class="img-thumbnail" src="holder.js/64x100" alt="Book Placeholder Image">
	</div>
	<div class = "media-body">
		<p>Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.</p>
	</div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class = "small text-muted">
    Website by Amit Bader
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand"><%= link_to "Bre Bader", root_path, id: "logo" %></div>
  </div>
  
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav pull-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Bio", bio_path %></li>
      <li><%= link_to "Resume", resume_path %></li>
      <li><%= link_to "Portfolio", portfolio_path %></li>
      <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Update Profile", edit_user_path(current_user) %></li>
            <% if current_user.admin? %>
              <li class="divider"></li>
              <li><%= link_to "All Users", users_path %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <%= render partial: "shared/flash_messages", flash: flash %> 
		<%= yield %>
		<%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_blogpost_form.html.erb
<%= form_for(@blogpost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
	<form class="form" role="form">

		<div class="form-group" >
			<%= f.text_field :subject, placeholder: "Enter the blog subject...", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.text_area :content, placeholder: "Compose new blog post...", class: "form-control" %>
		</div>

		<!-- <div class="form-group"> -->
			<%= f.submit "Post", class: "btn btn-lg btn-primary" %>
		<!-- </div> -->

	</form>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/static_pages/_carousel.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <div class="container carousel-background">
            <div class="carousel-caption">
              <h1>Dragons Bridge</h1>
              <p>A short story of love, worry and beautiful nature.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carousel-background">
            <div class="carousel-caption">
              <h1>Glass Mirrors</h1>
              <p>When a young girl's friend is stolen away, she must travel a strange land to rescue him.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carousel-background">
            <div class="carousel-caption">
              <h1>Works in progress</h1>
              <p>An assortment of short stories.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About the author</h1>
<p>This page will contian a biography and contact information for the author.</p>

app/views/static_pages/bio.html.erb
<% provide(:title, 'Biography') %>
<h1>Biography</h1>
<p>This page will contian a biography and contact information for the author.</p>

app/views/static_pages/home.html.erb
<%= render 'carousel' %>

<div class="container mainpage">
	<div class="row">
		<div class="col-lg-8">
			<h2>Blog</h2>
			<%= render @blogposts %>
		</div>
		<div class="col-lg-4">
			<%= render '/layouts/booklist' %>
		</div>
	</div>
</div>

app/views/static_pages/portfolio.html.erb
<% provide(:title, 'Portfolio') %>
<h1>Portfolio</h1>
<p>This page will contian the portfolio</p>

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>
<div class = "container resume">
	<h1>Breanna Bader</h1>
	<h2>Work Experience</h2>
	<h3><em>Blizzard Entertainment</em></h3>

	<div class = "container">
		<h3>Senior Game Master<span style="float: right;">2007-Present</span></h3>
		<p>Supervise teams each consisting of between eighteen and thirty customer support agents of varied tier level and with diverse skill backgrounds. Facilitate communication between several levels of management, and across departments.</p>
		<ul>
			<li>Create individualized coaching packages using data pulled from internal OLAP cube, personalized attention given to each agent’s successes and struggles, and dynamic career development plans.</li>
			<li>Daily utilization of Microsoft Office tools such as Outlook, Excel and One Note, SCRUM project/product development framework, Liveperson webchat interface, and internal employee management and contact management tools and systems.</li>
			<li>Direct or participate in daily standup huddles as well as weekly one on one and monthly team meetings.</li>
			<li>Compile and deliver post mortems and other documentation on team and agent performance on a weekly, monthly and quarterly basis.</li>
			<li>Crisis management for both customers and employees during sensitive or highly volatile situations.</li>
		</ul>
		<h3>Publishing Assistant</h3>
		<p>Collaborated with a highly creative team, as well as multiple departments and development teams, to expand extended universe content and deliver a transmedia narrative experience.</p>
		<ul>
			<li>Writing projects included FAQ content for product release press tour events, flavor copy for licensed products and in game lore, product reviews for public relations/marketing departments, fictional backgrounds produced for intellectual property characters and stories for internal development wiki, short story pitches, assisting with feedback on external submissions, brainstorming future projects such as Project Blackstone and Shadows of the Horde novel.</li>
			<li>Managed organizational tasks such as converting PDFs of graphic novels for internal library to searchable format, researching and compiling visual references for external artists, preparing and scanning pages to be sent to outside vendor (DC Comics) for publishing, gauging and compiling data on community response to future products, preparing music cues for digital adaption of licensed books, set up visiting authors at temporary workstations.</li>
		</ul>
		<h3>Quality Control</h3>
		<p>Responsible for analyzing and critiquing the written communication for multiple teams in order to help drive customer loyalty, raise satisfaction scores, and improve performance.</p>
	</div>

	<h3>Apple Inc. (Volt) <span style="float: right;">2005 - 2007</span></h3>
	<div class = "container"> 
		<h3>iTunes Store Customer Support</h3>
		<p>Responsible for addressing Emails from iTunes store customers while building skills in tailoring pre- formatted Email responses and investigating complex customer issues.</p>
	</div>

	<h3>Serengeti Systems Inc. <span style="float: right;">2006</span></h3> 
	<div class="container">
		<h3>Office Manager</h3>
		<p>Served as primary intermediary between customers, sales department, and developers. Required independent work and research, self motivation and organization, and a propensity for extremely rapid acquisition of new concepts and skills.</p>
	</div>

	<h2>Education</h2>
	<h3>Austin Community College – Austin, TX</h3>
	<ul>
		<li>Worked towards multiple majors in Philosophy, Comparative Religion and Psychology.</li>
		<li>University of Mary-Hardin Baylor – Belton, TX</li>
		<li>Focus on Comparative Religion and Psychology</li>
	</ul>
</div>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	|	<%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <form class="form" role= "form">

            <div class = "form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class = "form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: "form-control" %>
          </div>

            <div class = "form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control" %>
          </div>

            <div class = "form-group">
              <%= f.label :password_confirmation, "Confirm Password" %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>

          <div class = "form-group">
              <%= f.submit "Save changes", class: "btn btn-lg btn-primary" %>
            </div>

        </form>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

			<form class="form" role= "form">

			    	<div class = "form-group">
				      <%= f.label :name %>
				      <%= f.text_field :name, class: "form-control" %>
				    </div>

				    <div class = "form-group">
				      <%= f.label :email %>
				      <%= f.text_field :email, class: "form-control" %>
					</div>

				    <div class = "form-group">
				      <%= f.label :password %>
				      <%= f.password_field :password, class: "form-control" %>
					</div>

				    <div class = "form-group">
				      <%= f.label :password_confirmation, "Confirmation" %>
				      <%= f.password_field :password_confirmation, class: "form-control" %>
					</div>

					<div class = "form-group">
				      <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>
				    </div>

		    </form>
	    <% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>
<% if current_user.admin? %>
	<div class="container">
		<%= render 'shared/blogpost_form' %>
	</div>
<% end %>

<% if @user.blogposts.count != 0 %>
<div class="container">
  <h3>Blogposts (<%= @user.blogposts.count %>)</h3>
  <ol class="microposts">
    <%= render @blogposts %>
  </ol>
  <%= will_paginate @blogposts, renderer: BootstrapPagination::Rails %>
</div>
<% end %>